//! # cells/ai.rs
//!
//! AI cell evaluator — OpenAI-compatible chat completions.
//!
//! ## Role in the system
//!
//! A regular `api` cell with `endpoint: model:foo` returns a stub. For
//! a real call to an OpenAI-compatible API, an `api` cell with
//! `endpoint: https://api.openai.com/v1/chat/completions` and
//! `headers: { Authorization: "Bearer ..." }` is what you want. This
//! module wires the request up correctly so the cell's value comes
//! back as a real LLM response.
//!
//! ## Depends on
//!
//! - `reqwest` — async HTTP client.
//! - `crate::types` — `Cell`, `CellValue`, `CallerContext`, `Effect`.
//!
//! ## Used by
//!
//! - The engine's `get` for `api` cells. This is a thin shim — most
//!   LLM use is via the standard `api` evaluator with a real HTTP
//!   endpoint. This module exists to formalize the request shape and
//!   to provide a typed response.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::error::{Error, Result};
use crate::types::{now_millis, Cell, CellStatus, CellValue, Effect};

/// A chat-completion request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiRequest {
    /// The model name (e.g. `"gpt-4o-mini"`, `"claude-sonnet-4-5"`).
    pub model: String,
    /// The messages in the conversation.
    pub messages: Vec<AiMessage>,
    /// Optional sampling temperature, in [0, 2].
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    /// Optional maximum tokens to generate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    /// Optional nucleus sampling cutoff.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
    /// Optional stop sequences.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub stop: Vec<String>,
}

/// A single message in a chat-completion request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiMessage {
    /// The role (`"system"`, `"user"`, `"assistant"`, or `"tool"`).
    pub role: String,
    /// The message content.
    pub content: String,
    /// Optional name (for tool messages).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl AiMessage {
    /// Convenience constructor for a `user` message.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: "user".into(),
            content: content.into(),
            name: None,
        }
    }
    /// Convenience constructor for a `system` message.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: "system".into(),
            content: content.into(),
            name: None,
        }
    }
    /// Convenience constructor for an `assistant` message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: "assistant".into(),
            content: content.into(),
            name: None,
        }
    }
}

/// A chat-completion response (subset of the OpenAI shape).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiResponse {
    /// The model that was actually used.
    pub model: String,
    /// The assistant's reply.
    pub content: String,
    /// Token usage.
    pub usage: AiUsage,
    /// The finish reason (`"stop"`, `"length"`, `"tool_calls"`, etc).
    pub finish_reason: Option<String>,
}

/// Token-usage information.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AiUsage {
    /// Tokens consumed by the prompt.
    pub prompt_tokens: u32,
    /// Tokens generated by the model.
    pub completion_tokens: u32,
    /// Total tokens consumed.
    pub total_tokens: u32,
}

/// Evaluate an AI cell. Parses the cell's `endpoint` for a real
/// chat-completions URL, builds the request from the cell's
/// `headers` and the caller's `input`, and returns the response.
///
/// The `endpoint` should be the full URL of a chat-completions
/// endpoint. The cell's `headers` must contain the
/// `Authorization` header (and optionally other provider-specific
/// headers). The model name is read from the cell's
/// `headers["model"]` or from the `model:foo` URL fragment.
///
/// The `input` is the user message. If it's a string, it's wrapped
/// in a single `user` message. If it's an array, each element is
/// treated as a message.
pub async fn evaluate_ai(cell: Cell, _ctx: crate::types::CallerContext, input: Option<Value>) -> CellValue {
    let started = now_millis();
    let endpoint = match &cell.def.endpoint {
        Some(e) => e.clone(),
        None => return CellValue::err("ai cell has no endpoint"),
    };

    if endpoint.starts_with("model:") {
        // Stub path — return a synthetic response.
        let model = endpoint.trim_start_matches("model:").to_string();
        return CellValue {
            data: json!({
                "model": model,
                "content": format!("[stub response for {model}]"),
                "usage": { "prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0 },
                "finish_reason": "stop",
            }),
            status: CellStatus::Ready,
            computed_at: Some(now_millis()),
            error: None,
            effects: vec![Effect::Model {
                provider: model,
                tokens_in: None,
                tokens_out: None,
            }],
        };
    }

    // Build the request from the cell's headers + input.
    let model = cell
        .def
        .headers
        .get("model")
        .cloned()
        .unwrap_or_else(|| "unknown".to_string());
    let temperature = cell
        .def
        .headers
        .get("temperature")
        .and_then(|s| s.parse().ok());
    let max_tokens = cell
        .def
        .headers
        .get("max_tokens")
        .and_then(|s| s.parse().ok());

    let messages: Vec<AiMessage> = match input {
        Some(Value::String(s)) => vec![AiMessage::user(s)],
        Some(Value::Array(items)) => items
            .into_iter()
            .filter_map(|item| {
                if let Value::Object(map) = item {
                    Some(AiMessage {
                        role: map
                            .get("role")
                            .and_then(|v| v.as_str())
                            .unwrap_or("user")
                            .to_string(),
                        content: map
                            .get("content")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        name: map.get("name").and_then(|v| v.as_str()).map(String::from),
                    })
                } else {
                    None
                }
            })
            .collect(),
        _ => vec![],
    };

    let request = AiRequest {
        model: model.clone(),
        messages,
        temperature,
        max_tokens,
        top_p: None,
        stop: vec![],
    };

    // Issue the request.
    let client = reqwest::Client::new();
    let mut req = client.post(&endpoint);
    for (k, v) in &cell.def.headers {
        if k != "model" && k != "temperature" && k != "max_tokens" {
            req = req.header(k.as_str(), v.as_str());
        }
    }
    let response = match req.json(&request).send().await {
        Ok(r) => r,
        Err(e) => return CellValue::err(format!("{e}")),
    };

    let status = response.status();
    let body: Value = match response.json().await {
        Ok(v) => v,
        Err(e) => return CellValue::err(format!("{e}")),
    };
    if !status.is_success() {
        return CellValue::err(format!("HTTP {}: {}", status.as_u16(), body));
    }

    // Parse the OpenAI-shaped response.
    let content = body["choices"][0]["message"]["content"]
        .as_str()
        .unwrap_or("")
        .to_string();
    let model_resp = body["model"].as_str().unwrap_or(&model).to_string();
    let usage = AiUsage {
        prompt_tokens: body["usage"]["prompt_tokens"].as_u64().unwrap_or(0) as u32,
        completion_tokens: body["usage"]["completion_tokens"].as_u64().unwrap_or(0) as u32,
        total_tokens: body["usage"]["total_tokens"].as_u64().unwrap_or(0) as u32,
    };
    let finish_reason = body["choices"][0]["finish_reason"]
        .as_str()
        .map(String::from);
    let response = AiResponse {
        model: model_resp.clone(),
        content,
        usage,
        finish_reason,
    };

    let duration = now_millis().saturating_sub(started);
    CellValue {
        data: serde_json::to_value(&response).unwrap_or(Value::Null),
        status: CellStatus::Ready,
        computed_at: Some(now_millis()),
        error: None,
        effects: vec![
            Effect::Model {
                provider: model_resp,
                tokens_in: Some(response.usage.prompt_tokens as u64),
                tokens_out: Some(response.usage.completion_tokens as u64),
            },
            Effect::Compute { ms: duration },
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{CellDef, CellKind};

    fn ai_cell(endpoint: &str) -> Cell {
        Cell::new(CellDef {
            id: "ai".into(),
            kind: CellKind::Api,
            endpoint: Some(endpoint.to_string()),
            ..Default::default()
        })
    }

    #[tokio::test]
    async fn model_pseudo_endpoint_returns_synthetic() {
        let cell = ai_cell("model:gpt-4o-mini");
        let v = evaluate_ai(
            cell,
            crate::types::CallerContext::default(),
            Some(Value::String("hi".into())),
        )
        .await;
        assert!(v.is_ready());
        assert_eq!(v.data["model"], "gpt-4o-mini");
    }

    #[tokio::test]
    async fn missing_endpoint_errors() {
        let cell = Cell::new(CellDef {
            id: "ai".into(),
            kind: CellKind::Api,
            ..Default::default()
        });
        let v = evaluate_ai(
            cell,
            crate::types::CallerContext::default(),
            Some(Value::String("hi".into())),
        )
        .await;
        assert!(v.is_error());
    }

    #[test]
    fn ai_message_user() {
        let m = AiMessage::user("hello");
        assert_eq!(m.role, "user");
        assert_eq!(m.content, "hello");
    }

    #[test]
    fn ai_message_system() {
        let m = AiMessage::system("you are helpful");
        assert_eq!(m.role, "system");
    }

    #[test]
    fn ai_message_assistant() {
        let m = AiMessage::assistant("hi there");
        assert_eq!(m.role, "assistant");
    }

    #[test]
    fn ai_response_serializable() {
        let r = AiResponse {
            model: "gpt-4o".into(),
            content: "hi".into(),
            usage: AiUsage {
                prompt_tokens: 10,
                completion_tokens: 5,
                total_tokens: 15,
            },
            finish_reason: Some("stop".into()),
        };
        let s = serde_json::to_string(&r).unwrap();
        assert!(s.contains("\"model\":\"gpt-4o\""));
        assert!(s.contains("\"total_tokens\":15"));
    }

    #[test]
    fn ai_usage_default() {
        let u = AiUsage::default();
        assert_eq!(u.total_tokens, 0);
    }
}
